modules:
  # other useful stuff
  - repo: git@github.com:tmux-plugins/tpm.git
    pull_only: true
    link: none
    location: ~/.tmux/plugins/tpm
    name: tpm
  - repo: git@github.com:junegunn/vim-plug.git
    pull_only: true
    link: post
    mappings:
      # skip everything else
      - match: '.*'
        skip: true
      - match: '\/plug\.vim$'
        target_dir: ~/.vim/autoload/
    name: vim-plug
  - repo: git@github.com:eendroroy/alacritty-theme.git
    pull_only: true
    link: post
    mappings:
      # skip everything else
      - match: '.*'
        skip: true
      - match: '\/themes/.*\.y(a)?ml$'
        target_dir: ~/.config/alacritty/colors
    name: alacritty-theme


